// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbov1qAXe8nsLUm-9pcm-8YvkOEQt7LBw',
    appId: '1:136237959521:web:3dba2e23e8afcd97935d20',
    messagingSenderId: '136237959521',
    projectId: 'foolishfashionstore-384509',
    authDomain: 'foolishfashionstore-384509.firebaseapp.com',
    storageBucket: 'foolishfashionstore-384509.appspot.com',
    measurementId: 'G-CEFGB8JXXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIgUp9-MXMg4iSS_i2dz0qYOXYvPUs1RQ',
    appId: '1:136237959521:android:2df30bc674e4da84935d20',
    messagingSenderId: '136237959521',
    projectId: 'foolishfashionstore-384509',
    storageBucket: 'foolishfashionstore-384509.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSa3ag5oOC13J4lkTp_HbzG9azN6F1HvA',
    appId: '1:136237959521:ios:5cf32cb44cd45509935d20',
    messagingSenderId: '136237959521',
    projectId: 'foolishfashionstore-384509',
    storageBucket: 'foolishfashionstore-384509.appspot.com',
    iosBundleId: 'com.example.fashionstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSa3ag5oOC13J4lkTp_HbzG9azN6F1HvA',
    appId: '1:136237959521:ios:5cf32cb44cd45509935d20',
    messagingSenderId: '136237959521',
    projectId: 'foolishfashionstore-384509',
    storageBucket: 'foolishfashionstore-384509.appspot.com',
    iosBundleId: 'com.example.fashionstore',
  );
}
